const additioncalCurrenciesData = [
    { name: "US Dollar", symbol: "USD" },
    { name: "Canadian Dollar", symbol: "CAD" },
    { name: "Euro", symbol: "EUR" },
    { name: "United Arab Emirates Dirham", symbol: "AED" },
    { name: "Albanian Lek", symbol: "ALL" },
    { name: "Armenian Dram", symbol: "AMD" },
    { name: "Argentine Peso", symbol: "ARS" },
    { name: "Australian Dollar", symbol: "AUD" },
    { name: "Bosnia-Herzegovina Convertible Mark", symbol: "BAM" },
    { name: "Bangladeshi Taka", symbol: "BDT" },
    { name: "Bulgarian Lev", symbol: "BGN" },
    { name: "Bahraini Dinar", symbol: "BHD" },
    { name: "Burundian Franc", symbol: "BIF" },
    { name: "Brunei Dollar", symbol: "BND" },
    { name: "Bolivian Boliviano", symbol: "BOB" },
    { name: "Brazilian Real", symbol: "BRL" },
    { name: "Botswanan Pula", symbol: "BWP" },
    { name: "Belarusian Ruble", symbol: "BYN" },
    { name: "Congolese Franc", symbol: "CDF" },
    { name: "Swiss Franc", symbol: "CHF" },
    { name: "Chilean Peso", symbol: "CLP" },
    { name: "Chinese Yuan", symbol: "CNY" },
    { name: "Colombian Peso", symbol: "COP" },
    { name: "Costa Rican Colón", symbol: "CRC" },
    { name: "Czech Republic Koruna", symbol: "CZK" },
    { name: "Danish Krone", symbol: "DKK" },
    { name: "Dominican Peso", symbol: "DOP" },
    { name: "Algerian Dinar", symbol: "DZD" },
    { name: "Egyptian Pound", symbol: "EGP" },
    { name: "Ethiopian Birr", symbol: "ETB" },
    { name: "British Pound Sterling", symbol: "GBP" },
    { name: "Georgian Lari", symbol: "GEL" },
    { name: "Ghanaian Cedi", symbol: "GHS" },
    { name: "Guatemalan Quetzal", symbol: "GTQ" },
    { name: "Hong Kong Dollar", symbol: "HKD" },
    { name: "Honduran Lempira", symbol: "HNL" },
    { name: "Croatian Kuna", symbol: "HRK" },
    { name: "Hungarian Forint", symbol: "HUF" },
    { name: "Indonesian Rupiah", symbol: "IDR" },
    { name: "Israeli New Sheqel", symbol: "ILS" },
    { name: "Indian Rupee", symbol: "INR" },
    { name: "Iraqi Dinar", symbol: "IQD" },
    { name: "Iranian Rial", symbol: "IRR" },
    { name: "Icelandic Króna", symbol: "ISK" },
    { name: "Jamaican Dollar", symbol: "JMD" },
    { name: "Jordanian Dinar", symbol: "JOD" },
    { name: "Japanese Yen", symbol: "JPY" },
    { name: "Kenyan Shilling", symbol: "KES" },
    { name: "Cambodian Riel", symbol: "KHR" },
    { name: "South Korean Won", symbol: "KRW" },
    { name: "Kuwaiti Dinar", symbol: "KWD" },
    { name: "Kazakhstani Tenge", symbol: "KZT" },
    { name: "Lebanese Pound", symbol: "LBP" },
    { name: "Sri Lankan Rupee", symbol: "LKR" },
    { name: "Moroccan Dirham", symbol: "MAD" },
    { name: "Moldovan Leu", symbol: "MDL" },
    { name: "Myanma Kyat", symbol: "MMK" },
    { name: "Macanese Pataca", symbol: "MOP" },
    { name: "Mauritian Rupee", symbol: "MUR" },
    { name: "Mexican Peso", symbol: "MXN" },
    { name: "Malaysian Ringgit", symbol: "MYR" },
    { name: "Namibian Dollar", symbol: "NAD" },
    { name: "Nigerian Naira", symbol: "NGN" },
    { name: "Nicaraguan Córdoba", symbol: "NIO" },
    { name: "Norwegian Krone", symbol: "NOK" },
    { name: "Nepalese Rupee", symbol: "NPR" },
    { name: "New Zealand Dollar", symbol: "NZD" },
    { name: "Omani Rial", symbol: "OMR" },
    { name: "Panamanian Balboa", symbol: "PAB" },
    { name: "Peruvian Nuevo Sol", symbol: "PEN" },
    { name: "Philippine Peso", symbol: "PHP" },
    { name: "Pakistani Rupee", symbol: "PKR" },
    { name: "Polish Zloty", symbol: "PLN" },
    { name: "Paraguayan Guarani", symbol: "PYG" },
    { name: "Qatari Rial", symbol: "QAR" },
    { name: "Romanian Leu", symbol: "RON" },
    { name: "Serbian Dinar", symbol: "RSD" },
    { name: "Russian Ruble", symbol: "RUB" },
    { name: "Rwandan Franc", symbol: "RWF" },
    { name: "Saudi Riyal", symbol: "SAR" },
    { name: "Swedish Krona", symbol: "SEK" },
    { name: "Singapore Dollar", symbol: "SGD" },
    { name: "Syrian Pound", symbol: "SYP" },
    { name: "Thai Baht", symbol: "THB" },
    { name: "Tunisian Dinar", symbol: "TND" },
    { name: "Tongan Paʻanga", symbol: "TOP" },
    { name: "Turkish Lira", symbol: "TRY" },
    { name: "Trinidad and Tobago Dollar", symbol: "TTD" },
    { name: "New Taiwan Dollar", symbol: "TWD" },
    { name: "Tanzanian Shilling", symbol: "TZS" },
    { name: "Ukrainian Hryvnia", symbol: "UAH" },
    { name: "Ugandan Shilling", symbol: "UGX" },
    { name: "Uruguayan Peso", symbol: "UYU" },
    { name: "Uzbekistan Som", symbol: "UZS" },
    { name: "Venezuelan Bolívar", symbol: "VEF" },
    { name: "Vietnamese Dong", symbol: "VND" },
    { name: "CFA Franc BEAC", symbol: "XAF" },
    { name: "CFA Franc BCEAO", symbol: "XOF" },
    { name: "South African Rand", symbol: "ZAR" },
    { name: "HSR", symbol: "HSR" },
    { name: "USD", symbol: "USD" },
    { name: "PAI", symbol: "PAI" },
    { name: "ETHOS", symbol: "ETHOS" },
    { name: "BCP", symbol: "BCP" },
    { name: "CAIX", symbol: "CAIX" },
    { name: "SPR", symbol: "SPR" },
    { name: "TRUST", symbol: "TRUST" },
    { name: "OPAL", symbol: "OPAL" },
    { name: "EUR", symbol: "EUR" },
    { name: "BRZX", symbol: "BRZX" },
    { name: "NOBS", symbol: "NOBS" },
    { name: "$$$", symbol: "$$$" },
    { name: "CON", symbol: "CON" },
    { name: "$PAC", symbol: "$PAC" },
    { name: "XGOX", symbol: "XGOX" },
    { name: "GBP", symbol: "GBP" },
    { name: "IG", symbol: "IG" },
    { name: "ITT", symbol: "ITT" },
    { name: "GIO", symbol: "GIO" },
    { name: "TRY", symbol: "TRY" },
    { name: "EL", symbol: "EL" },
    { name: "CLPC", symbol: "CLPC" },
    { name: "RLT", symbol: "RLT" },
    { name: "DANC", symbol: "DANC" },
    { name: "MSCN", symbol: "MSCN" },
    { name: "GYC", symbol: "GYC" },
    { name: "FNC", symbol: "FNC" },
    { name: "IFAN", symbol: "IFAN" },
    { name: "PIN", symbol: "PIN" },
    { name: "eETT", symbol: "eETT" },
    { name: "ITI", symbol: "ITI" },
    { name: "wETT", symbol: "wETT" },
    { name: "BPC", symbol: "BPC" },
    { name: "MCR", symbol: "MCR" },
    { name: "FirstBlood", symbol: "FirstBlood" },
    { name: "ETHP", symbol: "ETHP" },
    { name: "DOLLAR", symbol: "DOLLAR" },
    { name: "RBM", symbol: "RBM" },
    { name: "FU", symbol: "FU" },
    { name: "OD", symbol: "OD" },
    { name: "LKK1Y", symbol: "LKK1Y" },
    { name: "XAG", symbol: "XAG" },
    { name: "_2B4T", symbol: "_2B4T" }
];
export default additioncalCurrenciesData;
